# Default values for nacos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  mode: cluster
  #mode: cluster

nameOverride: nacos
fullnameOverride: nacos
############################nacos###########################
nacos:
  image:
    repository: registry.cn-beijing.aliyuncs.com/kubegemsapp/nacos-server
    tag: 2.0.2
    pullPolicy: IfNotPresent
  plugin:
    enable: true
    image:
      repository: registry.cn-beijing.aliyuncs.com/kubegemsapp/nacos-peer-finder-plugin
      tag: 1.1
  replicaCount: 3
  domainName: cluster.local
  preferhostmode: hostname
  serverPort: 8848
  health:
    enabled: true
  storage:
    type: mysql
    db:
      host: 192.168.10.106
      name: nacos
      port: 31540
      username: nacos
      password: "123456"
      param: >-
        characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false

persistence:
  enabled: true
  data:
    accessModes:
      - ReadWriteOnce
    storageClassName: nfs-storage
    resources:
      requests:
        storage: 2Gi


service:
  #type: ClusterIP
  type: NodePort
  port: 8848
  #nodePort: 30000


ingress:
  enabled: false
  annotations: { }
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: nacos.example.com
      paths: []

  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "1"
    memory: 2.5Gi
  requests:
    cpu: 500m
    memory: 2Gi
annotations: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
